// License:
// 
// Rosetta
// Export -> ScenLang
// 
// 
// 
// 	(c) Jeroen P. Broks, 2023, 2025
// 
// 		This program is free software: you can redistribute it and/or modify
// 		it under the terms of the GNU General Public License as published by
// 		the Free Software Foundation, either version 3 of the License, or
// 		(at your option) any later version.
// 
// 		This program is distributed in the hope that it will be useful,
// 		but WITHOUT ANY WARRANTY; without even the implied warranty of
// 		MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// 		GNU General Public License for more details.
// 		You should have received a copy of the GNU General Public License
// 		along with this program.  If not, see <http://www.gnu.org/licenses/>.
// 
// 	Please note that some references to data like pictures or audio, do not automatically
// 	fall under this licenses. Mostly this is noted in the respective files.
// 
// Version: 25.11.15
// End License
//#include "../Class/AllClasses.hpp"
#include "../Rosetta.hpp"
#include "SlyvTime.hpp"
#include "SlyvStream.hpp"

using namespace Slyvina::Units;
using namespace Slyvina::Rosetta::Class;

namespace Slyvina {
	namespace Rosetta {
		namespace Export {
        //internal class XScenLang:XBase {
                static void SL_Export(_ProjectData* D, String language) {
                        String Head = "[rem]\nFile Generated By Rosetta\n(c) Copyright "+Now()+" Jeroen P. Broks\nThese files and their content are property of Jeroen P. Broks and may NOT be removed without prior WRITTEN permission by the owner\n\n";
                        auto Entries { D->Scenario->AllEntries()};
                        if (Entries != nullptr) {
                                for (auto E : *Entries) {
                                        String Out{Head}; //= new StringBuilder(Head);
                                        auto Entry = (*D->Scenario)[E]; //->GetEntry(E);
                                        auto Tags = Entry->LTags();
                                        Out += "[tags]\n";
                                        for (auto T : *Tags) Out += T+"\n";
                                        Out += "\n\n\n[scenario]\n\n";
                                        for (auto T : *Tags) {
                                                Out += "-- Tag: "+T+"\n";
                                                auto Tag{D->Scenario->GetTag(E,T)}; //= D.Scenario[E, T];
                                                for (auto pn = 0; pn < Tag->PageCount(); pn++) {
                                                        auto Page{D->Scenario->GetPage(E,T,pn)}; //= D.Scenario[E, T, pn];
                                                        auto LPage{D->Scenario->GetLang(E,T,pn,language)}; //= D.Scenario[E, T, pn, language];
                                                        Out += "@"+T+"\n";
                                                        Out += "!"+Page->PicDir()+"\n";
                                                        Out += "*"+LPage->Header()+"\n";
                                                        Out += ":"+Page->PicSpecific()+"\n";
                                                        Out += "%"+Page->AltFont()+"\n";
                                                        Out += "$"+Page->Audio()+"\n";
                                                        auto C { LPage->LContent()};
                                                        for (auto CL : *C) Out += "#"+CL+"\n";
                                                        Out += "\n";
                                                }
                                                Out += "\n";
                                        }
                                        //QuickStream.SaveString($"{D.ExportDir}/{language}/{E}", Out, true);
                                        SaveString(D->ExportDir()+"/"+language+"/"+E,Out);
                                }
                        }
                }

                //internal XScenLang() => Reg("ScenLang", this);
                void Init_X_ScenLang() {
					XBase::Reg("ScenLang",SL_Export);
                }
        }
	}
}

